"""The Alembic migrations must reproduce exactly what the models declare."""

from __future__ import annotations

from pathlib import Path

from alembic import command
from alembic.config import Config

ROOT = Path(__file__).resolve().parent.parent


def _config(db_path: Path) -> Config:
    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(ROOT / "alembic"))
    cfg.set_main_option("sqlalchemy.url", f"sqlite+aiosqlite:///{db_path}")
    return cfg


def test_migrations_match_models(tmp_path):
    cfg = _config(tmp_path / "m.db")
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected on drift


def test_downgrade_to_base(tmp_path):
    cfg = _config(tmp_path / "d.db")
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
